#!/usr/bin/env python3
"""Build the JetBrains API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'JetBrains Platform',
        "color": '#FF318C',
        "closed": True,
        "stations": [
        ('Space', (640, 260)),
        ('TeamCity', (830, 398)),
        ('YouTrack', (758, 622)),
        ('Hub', (522, 622)),
        ('Marketplace', (450, 398)),
        ],
    },
]

URL_OVERRIDES = {
    'Space': 'https://apis.apis.io/apis/jetbrains/space-api/',
    'TeamCity': 'https://apis.apis.io/apis/jetbrains/teamcity-api/',
    'YouTrack': 'https://apis.apis.io/apis/jetbrains/youtrack-api/',
    'Hub': 'https://apis.apis.io/apis/jetbrains/hub-api/',
    'Marketplace': 'https://apis.apis.io/apis/jetbrains/marketplace-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The JetBrains API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: jetbrains/openapi · github.com/api-evangelist/jetbrains',
        out_dir=Path(__file__).resolve().parent,
        out_basename='jetbrains-subway-map',
        provider_id='jetbrains',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
